# Generated by Django 3.0.7 on 2022-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='by_journalist',
        ),
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='leaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
